version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: my_postgres_container
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - my_network

    backend:
        image: sorteo-backend
        container_name: sorteo-backend
        command: npm run dev
        build:
            context: ./backEnd
            dockerfile: Dockerfile
        env_file: .env.production
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        networks:
            - my_network

    frontend:
        build:
            context: ./frontEnd
            dockerfile: Dockerfile
        container_name: sorteo-front
        env_file: .env.production
        ports:
            - '80:80'
        depends_on:
            - backend
        networks:
            - my_network

networks:
    my_network:

volumes:
    postgres_data:
